/** Env names only — never commit values. Server / cloud runtime. */
export const ENV = {
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GEMINI_TEXT_MODEL: "GEMINI_TEXT_MODEL",
  GEMINI_IMAGE_MODEL: "GEMINI_IMAGE_MODEL",
  PEXELS_API_KEY: "PEXELS_API_KEY",
  CUTLINE_PUBLIC_URL: "CUTLINE_PUBLIC_URL",
  IG_APP_ID: "IG_APP_ID",
  IG_APP_SECRET: "IG_APP_SECRET",
  YT_CLIENT_ID: "YT_CLIENT_ID",
  YT_CLIENT_SECRET: "YT_CLIENT_SECRET",
  CANVA_CLIENT_ID: "CANVA_CLIENT_ID",
  CANVA_CLIENT_SECRET: "CANVA_CLIENT_SECRET",
  X_CLIENT_ID: "X_CLIENT_ID",
  X_CLIENT_SECRET: "X_CLIENT_SECRET",
  TIKTOK_CLIENT_KEY: "TIKTOK_CLIENT_KEY",
  TIKTOK_CLIENT_SECRET: "TIKTOK_CLIENT_SECRET",
  TELEGRAM_BOT_TOKEN: "TELEGRAM_BOT_TOKEN",
} as const;
